[parity]
base_path = "./data"
no_persistent_txqueue = true
chain = "./spec.json"
keys_path = "./keys"

[network]
# Parity will sync by downloading latest state first. Node will be operational in couple minutes.
warp = false

[rpc]
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "parity", "parity_set", "traces", "rpc"]
cors = ["*"]



[footprint]
tracing = "on"
pruning = "archive"